name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout pushed commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: install dependencies
      run: |
        docker-compose build
        docker-compose run --rm web bundle install
        docker-compose run --rm web yarn install --check-files
    - name: use stable version of Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: build webpacker
      run: docker-compose run --rm web rails webpacker:compile
    - name: run tests
      run: docker-compose run --rm web rails test


