name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout pushed commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: install Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: install dependencies
      run: |
        gem install bundler
        bundle install --path vendor/bundle
        yarn install
    - name: run webpacker install
      run: |
        bundle exec rails webpacker:install
        bundle exec rails webpacker:compile RAILS_ENV=test
    - name: run test on docker-compose
      run: |
        docker-compose build
        docker-compose run --rm web bin/setup
        docker-compose run --rm web rails test

